{{ if .Values.apiWorker.persistence.lago_storage_data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-lago_storage_data'
  labels:
    app.kubernetes.io/component: api-worker
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/pvc-name: lago_storage_data
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  resources:
    requests:
      storage: '{{ .Values.apiWorker.persistence.lago_storage_data.capacity }}'
  {{ if .Values.apiWorker.persistence.lago_storage_data.storageClassName }}
  storageClassName: '{{ .Values.apiWorker.persistence.lago_storage_data.storageClassName }}'
  {{ end }}
  accessModes:
    - ReadWriteOnce

spec:
{{- end -}}