{{ if .Values.api.persistence.lago_storage_data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-lago-storage-data'
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/pvc-name: lago-storage-data
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  resources:
    requests:
      storage: '{{ .Values.api.persistence.lago_storage_data.capacity }}'
  {{ if .Values.api.persistence.lago_storage_data.storageClassName }}
  storageClassName: '{{ .Values.api.persistence.lago_storage_data.storageClassName }}'
  {{ end }}
  accessModes:
    - ReadWriteOnce
{{- end -}}