apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-api-clock'
  labels:
    app.kubernetes.io/component: api-clock
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api-clock
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api-clock
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: check-api
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking api port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-api 3000 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: api-clock
          image: '{{ .Values.apiClock.repository.image }}{{ if ne .Values.apiClock.repository.tag "" }}:{{ .Values.apiClock.repository.tag }}{{ end }}'
          env:
            - name: DATABASE_URL
              value: '{{ tpl .Values.apiClock.environment.DATABASE_URL . }}'
            - name: RAILS_ENV
              value: '{{ tpl .Values.apiClock.environment.RAILS_ENV . }}'
            - name: SENTRY_DSN
              value: '{{ tpl .Values.apiClock.environment.SENTRY_DSN . }}'
            - name: ENCRYPTION_PRIMARY_KEY
              value: '{{ tpl .Values.apiClock.environment.ENCRYPTION_PRIMARY_KEY . }}'
            - name: LAGO_API_URL
              value: '{{ tpl .Values.apiClock.environment.LAGO_API_URL . }}'
            - name: ENCRYPTION_KEY_DERIVATION_SALT
              value: '{{ tpl .Values.apiClock.environment.ENCRYPTION_KEY_DERIVATION_SALT . }}'
            - name: RAILS_LOG_TO_STDOUT
              value: '{{ tpl .Values.apiClock.environment.RAILS_LOG_TO_STDOUT . }}'
            - name: REDIS_URL
              value: '{{ tpl .Values.apiClock.environment.REDIS_URL . }}'
            - name: SECRET_KEY_BASE
              value: '{{ tpl .Values.apiClock.environment.SECRET_KEY_BASE . }}'
            - name: ENCRYPTION_DETERMINISTIC_KEY
              value: '{{ tpl .Values.apiClock.environment.ENCRYPTION_DETERMINISTIC_KEY . }}'
            - name: LAGO_RSA_PRIVATE_KEY
              value: '{{ tpl .Values.apiClock.environment.LAGO_RSA_PRIVATE_KEY . }}'
            - name: RSA_PRIVATE_KEY
              value: '{{ tpl .Values.apiClock.environment.RSA_PRIVATE_KEY . }}'
          command:
            - ./scripts/start.clock.sh

