apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-api'
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-db
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking db port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-db 5432 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
        - name: check-redis
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking redis port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-redis 6379 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: api
          image: '{{ .Values.api.repository.image }}{{ if ne .Values.api.repository.tag "" }}:{{ .Values.api.repository.tag }}{{ end }}'
          ports:
            - name: api
              containerPort: 3000
          env:
            - name: LAGO_OAUTH_PROXY_URL
              value: '{{ tpl .Values.api.environment.LAGO_OAUTH_PROXY_URL . }}'
            - name: LAGO_REDIS_CACHE_URL
              value: '{{ tpl .Values.api.environment.LAGO_REDIS_CACHE_URL . }}'
            - name: LAGO_API_URL
              value: '{{ tpl .Values.api.environment.LAGO_API_URL . }}'
            - name: LAGO_PDF_URL
              value: '{{ tpl .Values.api.environment.LAGO_PDF_URL . }}'
            - name: LAGO_SIDEKIQ_WEB
              value: '{{ tpl .Values.api.environment.LAGO_SIDEKIQ_WEB . }}'
            - name: GOCARDLESS_CLIENT_ID
              value: '{{ tpl .Values.api.environment.GOCARDLESS_CLIENT_ID . }}'
            - name: SECRET_KEY_BASE
              value: '{{ tpl .Values.api.environment.SECRET_KEY_BASE . }}'
            - name: ENCRYPTION_DETERMINISTIC_KEY
              value: '{{ tpl .Values.api.environment.ENCRYPTION_DETERMINISTIC_KEY . }}'
            - name: DATABASE_URL
              value: '{{ tpl .Values.api.environment.DATABASE_URL . }}'
            - name: LAGO_AWS_S3_REGION
              value: '{{ tpl .Values.api.environment.LAGO_AWS_S3_REGION . }}'
            - name: LAGO_USE_GCS
              value: '{{ tpl .Values.api.environment.LAGO_USE_GCS . }}'
            - name: RAILS_ENV
              value: '{{ tpl .Values.api.environment.RAILS_ENV . }}'
            - name: LAGO_AWS_S3_BUCKET
              value: '{{ tpl .Values.api.environment.LAGO_AWS_S3_BUCKET . }}'
            - name: LAGO_FRONT_URL
              value: '{{ tpl .Values.api.environment.LAGO_FRONT_URL . }}'
            - name: LAGO_DISABLE_SEGMENT
              value: '{{ tpl .Values.api.environment.LAGO_DISABLE_SEGMENT . }}'
            - name: REDIS_URL
              value: '{{ tpl .Values.api.environment.REDIS_URL . }}'
            - name: LAGO_RSA_PRIVATE_KEY
              value: '{{ tpl .Values.api.environment.LAGO_RSA_PRIVATE_KEY . }}'
            - name: LAGO_AWS_S3_SECRET_ACCESS_KEY
              value: '{{ tpl .Values.api.environment.LAGO_AWS_S3_SECRET_ACCESS_KEY . }}'
            - name: LAGO_AWS_S3_ENDPOINT
              value: '{{ tpl .Values.api.environment.LAGO_AWS_S3_ENDPOINT . }}'
            - name: RAILS_LOG_TO_STDOUT
              value: '{{ tpl .Values.api.environment.RAILS_LOG_TO_STDOUT . }}'
            - name: GOCARDLESS_CLIENT_SECRET
              value: '{{ tpl .Values.api.environment.GOCARDLESS_CLIENT_SECRET . }}'
            - name: LAGO_GCS_PROJECT
              value: '{{ tpl .Values.api.environment.LAGO_GCS_PROJECT . }}'
            - name: RSA_PRIVATE_KEY
              value: '{{ tpl .Values.api.environment.RSA_PRIVATE_KEY . }}'
            - name: LAGO_AWS_S3_ACCESS_KEY_ID
              value: '{{ tpl .Values.api.environment.LAGO_AWS_S3_ACCESS_KEY_ID . }}'
            - name: LAGO_USE_AWS_S3
              value: '{{ tpl .Values.api.environment.LAGO_USE_AWS_S3 . }}'
            - name: LAGO_GCS_BUCKET
              value: '{{ tpl .Values.api.environment.LAGO_GCS_BUCKET . }}'
            - name: ENCRYPTION_KEY_DERIVATION_SALT
              value: '{{ tpl .Values.api.environment.ENCRYPTION_KEY_DERIVATION_SALT . }}'
            - name: ENCRYPTION_PRIMARY_KEY
              value: '{{ tpl .Values.api.environment.ENCRYPTION_PRIMARY_KEY . }}'
            - name: SENTRY_DSN
              value: '{{ tpl .Values.api.environment.SENTRY_DSN . }}'
          command:
            - ./scripts/start.sh

