apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-api'
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'

spec:
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
