{{ if .Values.db.persistence.lago_postgres_data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-lago-postgres-data'
  labels:
    app.kubernetes.io/component: db
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/pvc-name: lago-postgres-data
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  resources:
    requests:
      storage: '{{ .Values.db.persistence.lago_postgres_data.capacity }}'
  {{ if .Values.db.persistence.lago_postgres_data.storageClassName }}
  storageClassName: '{{ .Values.db.persistence.lago_postgres_data.storageClassName }}'
  {{ end }}
  accessModes:
    - ReadWriteOnce
{{- end -}}