apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-front'
  labels:
    app.kubernetes.io/component: front
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'

spec:
  selector:
    app.kubernetes.io/component: front
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
