apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-front'
  labels:
    app.kubernetes.io/component: front
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: front
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/component: front
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-api
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking api port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-api 3000 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: front
          image: '{{ .Values.front.repository.image }}{{ if ne .Values.front.repository.tag "" }}:{{ .Values.front.repository.tag }}{{ end }}'
          ports:
            - name: front
              containerPort: 80
          env:
            - name: LAGO_DISABLE_SIGNUP
              value: '{{ tpl .Values.front.environment.LAGO_DISABLE_SIGNUP . }}'
            - name: LAGO_OAUTH_PROXY_URL
              value: '{{ tpl .Values.front.environment.LAGO_OAUTH_PROXY_URL . }}'
            - name: API_URL
              value: '{{ tpl .Values.front.environment.API_URL . }}'
            - name: APP_ENV
              value: '{{ tpl .Values.front.environment.APP_ENV . }}'
            - name: CODEGEN_API
              value: '{{ tpl .Values.front.environment.CODEGEN_API . }}'

