apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-pdf'
  labels:
    app.kubernetes.io/component: pdf
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pdf
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pdf
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      containers:
        - name: pdf
          image: '{{ .Values.pdf.repository.image }}{{ if ne .Values.pdf.repository.tag "" }}:{{ .Values.pdf.repository.tag }}{{ end }}'

