apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-redis'
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'

spec:
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
