api:
  environment:
    DATABASE_URL: postgresql://lago:changeme@lago-db:5432/lago
    ENCRYPTION_DETERMINISTIC_KEY: your-encrpytion-deterministic-key
    ENCRYPTION_KEY_DERIVATION_SALT: your-encrpytion-derivation-salt
    ENCRYPTION_PRIMARY_KEY: your-encrpytion-primary-key
    GOCARDLESS_CLIENT_ID: ""
    GOCARDLESS_CLIENT_SECRET: ""
    LAGO_API_URL: http://localhost:3000
    LAGO_AWS_S3_ACCESS_KEY_ID: azerty123456
    LAGO_AWS_S3_BUCKET: bucket
    LAGO_AWS_S3_ENDPOINT: ""
    LAGO_AWS_S3_REGION: us-east-1
    LAGO_AWS_S3_SECRET_ACCESS_KEY: azerty123456
    LAGO_DISABLE_SEGMENT: ""
    LAGO_FRONT_URL: http://localhost
    LAGO_GCS_BUCKET: ""
    LAGO_GCS_PROJECT: ""
    LAGO_OAUTH_PROXY_URL: ""
    LAGO_PDF_URL: http://lago-pdf:3000
    LAGO_REDIS_CACHE_URL: redis://lago-redis:6379
    LAGO_RSA_PRIVATE_KEY: ""
    LAGO_SIDEKIQ_WEB: ""
    LAGO_USE_AWS_S3: "false"
    LAGO_USE_GCS: "false"
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: "true"
    REDIS_URL: redis://lago-redis:6379
    RSA_PRIVATE_KEY: ""
    SECRET_KEY_BASE: your-secret-key-base-hex-64
    SENTRY_DSN: ""
  persistence:
    lago_storage_data:
      capacity: 1Gi
      enabled: false
      storageClassName: ""
  repository:
    image: getlago/api
    tag: v0.16.0-alpha
apiClock:
  environment:
    DATABASE_URL: postgresql://lago:changeme@lago-db:5432/lago
    ENCRYPTION_DETERMINISTIC_KEY: your-encrpytion-deterministic-key
    ENCRYPTION_KEY_DERIVATION_SALT: your-encrpytion-derivation-salt
    ENCRYPTION_PRIMARY_KEY: your-encrpytion-primary-key
    LAGO_API_URL: http://localhost:3000
    LAGO_RSA_PRIVATE_KEY: ""
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: "true"
    REDIS_URL: redis://lago-redis:6379
    RSA_PRIVATE_KEY: ""
    SECRET_KEY_BASE: your-secret-key-base-hex-64
    SENTRY_DSN: ""
  repository:
    image: getlago/api
    tag: v0.16.0-alpha
apiWorker:
  environment:
    DATABASE_URL: postgresql://lago:changeme@db:5432/lago
    ENCRYPTION_DETERMINISTIC_KEY: your-encrpytion-deterministic-key
    ENCRYPTION_KEY_DERIVATION_SALT: your-encrpytion-derivation-salt
    ENCRYPTION_PRIMARY_KEY: your-encrpytion-primary-key
    GOCARDLESS_CLIENT_ID: ""
    GOCARDLESS_CLIENT_SECRET: ""
    LAGO_API_URL: http://localhost:3000
    LAGO_AWS_S3_ACCESS_KEY_ID: azerty123456
    LAGO_AWS_S3_BUCKET: bucket
    LAGO_AWS_S3_ENDPOINT: ""
    LAGO_AWS_S3_REGION: us-east-1
    LAGO_AWS_S3_SECRET_ACCESS_KEY: azerty123456
    LAGO_DISABLE_SEGMENT: ""
    LAGO_GCS_BUCKET: ""
    LAGO_GCS_PROJECT: ""
    LAGO_PDF_URL: http://lago-pdf:3000
    LAGO_REDIS_CACHE_URL: redis://lago-redis:6379
    LAGO_RSA_PRIVATE_KEY: ""
    LAGO_USE_AWS_S3: "false"
    LAGO_USE_GCS: "false"
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: "true"
    REDIS_URL: redis://lago-redis:6379
    RSA_PRIVATE_KEY: ""
    SECRET_KEY_BASE: your-secret-key-base-hex-64
    SENTRY_DSN: ""
  persistence:
    lago_storage_data:
      capacity: 1Gi
      enabled: false
      storageClassName: ""
  repository:
    image: getlago/api
    tag: v0.16.0-alpha
db:
  environment:
    PGDATA: /data/postgres
    POSTGRES_DB: lago
    POSTGRES_PASSWORD: changeme
    POSTGRES_USER: lago
  persistence:
    lago_postgres_data:
      capacity: 1Gi
      enabled: false
      storageClassName: ""
  repository:
    image: postgres
    tag: 14.0-alpine
front:
  environment:
    API_URL: http://localhost:3000
    APP_ENV: production
    CODEGEN_API: http://localhost:3000
    LAGO_DISABLE_SIGNUP: "false"
    LAGO_OAUTH_PROXY_URL: ""
  repository:
    image: getlago/front
    tag: v0.16.0-alpha
pdf:
  repository:
    image: getlago/lago-gotenberg
    tag: "7"
redis:
  persistence:
    lago_redis_data:
      capacity: 1Gi
      enabled: false
      storageClassName: ""
  repository:
    image: redis
    tag: 6.2-alpine
